version: "3.9"

services:

  postgres:
    image: postgres:16-alpine
    container_name: express_postgres_task

    restart: always

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: task_management_db

    ports:
      - "5435:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/schema.sql:/docker-entrypoint-initdb.d/schema.sql

volumes:
  postgres_data: